apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mern
  labels:
    role: frontend
    env: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      imagePullSecrets:
      - name: frontend-repo-secret
      containers:
      - name: frontend
        image: 729207654069.dkr.ecr.me-south-1.amazonaws.com/ecr-repo-1:51
        imagePullPolicy: Always
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://backend.amanpathakdevops.study/api/tasks"
        ports:
        - containerPort: 3000
