ami                         = "ami-0d2b3011fe4d8ad42"
instance_type               = "t3.micro"
key_name                    = "key-bahrain"
instance_count              = 3
env                         = ["development", "staging", "production"]
subnet_id                   = "subnet-0aada5a074d93f0d3"
associate_public_ip_address = false
aws_Region                  = "me-south-1"
cidr_block                  = "10.0.0.0/16"
availability_zones           = ["me-south-1a", "me-south-1b", "me-south-1c"]
private_key_path            = "/home/amr-kedra/First-DevOps-Repo-For-Organization/Terraform/key-bahrain.pem"
repository_name             = "ecr-repo-1"
image_tag_mutability        = "MUTABLE"
vpc_cidr                    = "10.0.0.0/16"  # Ensure this covers all subnets
public_subnet_cidr          = "10.0.3.0/24"
cluster_cidr_blocks         = ["10.0.0.0/16"]  # No change required here
cluster_name                = "my-eks-cluster"
cluster_role_arn            = "arn:aws:iam::729207654069:role/EKS-Cluster-Admin"
desired_size                = 2
max_size                    = 5
min_size                    = 1
private_subnet_ids          = ["subnet-0e4f5g6h"]  # No change required
node_group_name             = "my-eks-node-group"
node_role_arn               = "arn:aws:iam::729207654069:role/EKS-Cluster-Admin"
worker_cidr_blocks          = ["10.0.1.0/24"]  # Changed based on valid range
node_count                  = 2
role_arn                    = "arn:aws:iam::729207654069:role/EKS-Cluster-Admin"
private_subnets             = ["10.0.1.0/24", "10.0.2.0/24"]  # Ensure these match your VPC CIDR range
private_subnet_b_cidr       = "10.0.2.0/24"  # Check this is valid and within the VPC CIDR
private_subnet_a_cidr       = "10.0.1.0/24"  # Same here, ensure it's valid
jump_server_private_ip      = "10.0.0.10"
public_subnet_ids           = ["subnet-12345678", "subnet-87654321"]
vpc_id                      = "EKS-VPCs"