ami                         = "ami-0d3cfbdc78e330d61"
instance_type               = "t3.medium"
key_name                    = "key-bahrain"
instance_count              = 3
env                         = ["development", "staging", "production"]
subnet_id                   = "subnet-0aada5a074d93f0d3"
associate_public_ip_address = false
cidr_block                  = "10.0.0.0/16"
availability_zones          = ["me-south-1a", "me-south-1b", "me-south-1c"]
private_key_path            = "/home/amr-kedra/First-DevOps-Repo-For-Organization/Terraform/key-bahrain.pem"
repository_name             = "ecr-repo-1"
image_tag_mutability        = "MUTABLE"
vpc_cidr                    = "10.0.0.0/16"   # Ensure this covers all subnets
cluster_cidr_blocks         = ["10.0.0.0/16"] # No change required here
cluster_role_arn            = "arn:aws:iam::729207654069:role/EKS-Cluster-Admin"
private_subnet_ids          = ["subnet-0e4f5g6h"] # No change required
node_group_name             = "my_EKS_node_group"
node_role_arn               = "arn:aws:iam::729207654069:role/EKS-Cluster-Admin"
worker_cidr_blocks          = ["10.0.1.0/24"] # Changed based on valid range
node_count                  = 2
role_arn                    = "arn:aws:iam::729207654069:role/EKS-Cluster-Admin"
private_subnets             = ["10.0.1.0/24", "10.0.2.0/24"] # Ensure these match your VPC CIDR range
jump_server_private_ip      = "10.0.0.10"
vpc_id                      = "EKS-VPCs"
public_subnet_cidrs         = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs        = ["10.0.3.0/24", "10.0.4.0/24"]
nat_gateway_subnet          = "10.0.1.0/24" # Change this as needed
tags = {
  Name = "MERN-VPC"
}
cluster_name     = "my-eks-cluster"
desired_capacity = 2
max_capacity     = 5
min_capacity     = 1
region           = "me-south-1"
