all:
  children:

    AWS-Jenkins-Server:
      hosts:
        aws-jenkins:
          ansible_host: 15.185.80.203
          ansible_user: ubuntu # or another username based on the AMI used
          ansible_ssh_private_key_file: ./key-bahrain.pem

    # masters:
    #   hosts:
    #     master:
    #       ansible_host: 192.168.1.4
    #       ansible_user: amrkedra
    #       ansible_ssh_private_key_file: ./vm-rsa-key

    # workers:
    #   hosts:
    #     worker:
    #       ansible_host: 192.168.1.9
    #       ansible_user: amrkedra
    #       ansible_ssh_private_key_file: ./vm-rsa-key

    # k8s_cluster:
    #   children:
    #     masters: {}
    #     workers: {}
