all:
  children:
    AWS-Jenkins-Server:
      hosts:
        aws-jenkins:
          ansible_host: 157.175.176.126 # Replace with your EC2 instance IP
          ansible_user: ubuntu # The username based on your AMI
          ansible_ssh_private_key_file: ./key-bahrain.pem

    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: amr-kedra

    # masters:
    #   hosts:
    #     master:
    #       ansible_host: 192.168.1.4
    #       ansible_user: amrkedra
    #       ansible_ssh_private_key_file: ./vm-rsa-key

    # workers:
    #   hosts:
    #     worker:
    #       ansible_host: 192.168.1.9
    #       ansible_user: amrkedra
    #       ansible_ssh_private_key_file: ./vm-rsa-key

    # k8s_cluster:
    #   children:
    #     masters: {}
    #     workers: {}
