pipeline {
    agent any

    stages {
        stage("Clone the Repo & Go to Terraform Folder") {
            steps {
                script {
                    // Clone the repository
                    git branch: 'main', url: 'https://github.com/amrkedra/MERN-Full-project.git'
                    
                    // Change directory to Terraform
                    dir('MERN-Infra-providing/Terraform') {
                        // Now you can run Terraform commands here
                    }
                }
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                    // Run Terraform init
                    sh 'terraform init --upgrade'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    // Run Terraform plan
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                input 'Approve Terraform Apply?'
                script {
                    // Use AWS credentials from Jenkins credentials store
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentials', credentialsId: 'aws-creds']
                    ]) {
                        // Run Terraform apply
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }
    }

    // post {
    //     always {
    //         script {
    //             // Archive Terraform state files
    //             archiveArtifacts artifacts: '**/terraform.tfstate', fingerprint: true
    //         }
    //     }
    // }
}
