pipeline {
    agent { label "master" }

    environment {
        // Set the Terraform home path
        TF_HOME = tool name: 'Terraform 1.0', type: 'TerraformInstallation'
    }

    stages {
        stage("Clone the Repo & Go to Terraform Folder") {
            steps {
                script {
                    // Clone the repository
                    git branch: 'main', url: 'https://github.com/amrkedra/MERN-Full-project.git'

                    // Change directory to Terraform
                    dir('MERN-Full-project/Terraform') {
                        // Print current directory to confirm
                        sh 'pwd'
                    }
                }
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                    // Set Terraform binary in the PATH
                    env.PATH = "${TF_HOME}:${env.PATH}"
                    
                    // Print Terraform version to verify
                    sh 'terraform --version'
                    
                    // Run Terraform init
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    // Run Terraform plan
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                input 'Approve Terraform Apply?'
                script {
                    // Run Terraform apply with auto-approve
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }

    post {
        always {
            // Archive the Terraform state file
            archiveArtifacts artifacts: '**/terraform.tfstate', fingerprint: true
        }
    }
}
